# Generated by Django 3.1.13 on 2022-06-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iknow_sgp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionname', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=2000)),
                ('bioprojectname', models.CharField(choices=[('PhenObs', 'Phenobs'), ('Glonaf', 'Glonaf'), ('sPlot', 'sPlot')], default='PhenObs', max_length=255)),
                ('associated_sgprojects', models.ManyToManyField(to='iknow_sgp.SGP')),
            ],
        ),
    ]
